### PR TITLE
Fix explorer dark mode issue and restructure scss

### LINKED ISSUE #155: [BUG] dark mode issue in explorer page
Explorer visualization page has white color padding under dark mode.

### PR DESCRIPTION
**Pull request by mengweieric**
### Description
- fix dark mode issue in explorer visualization page
- restructure scss for event analytics

### Issues Resolved
#155 
#156 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by ps48 — APPROVED** [review]

File: public/components/event_analytics/explorer/explorer.tsx [hunk 1]
```diff
@@ -1478,7 +1478,7 @@ export const Explorer = ({
         query,
       }}
     >
-      <div className="dscAppContainer">
+      <div className={`dscAppContainer${uiSettingsService.get('theme:darkMode') && ' explorer-dark'}`}>
```
Comment (joshuali925) [inline public/components/event_analytics/explorer/explorer.tsx:1481]: i don't remember if `theme:darkMode` is a boolean, if so then when `uiSettingsService.get('theme:darkMode')` is `false`, the className would be `dscAppContainerfalse`?

Comment (mengweieric) [reply public/components/event_analytics/explorer/explorer.tsx:1481]: it is boolean true when under dark mode, but is empty when not under dark mode therefore should not be seeing 'dscAppContainerfalse' case.

**Review by joshuali925 — APPROVED** [review]
