### PR TITLE
Fix window start backtick during MV creation

### LINKED ISSUE #1819: [BUG] MV creation issue when using `window.start` as a paramater.
**What is the bug?**
Create acceleration flyout fails to create an acceleration when `window.start` is used as a paramater in the MV aggregations. 

**How can one reproduce the bug?**
1. Go to create acceleration flyout
2. Click on create acceleration with MV and add `window.start` as a paramater
3. Scroll down to see the generated query
4. Click on create acceleration

**Work around**
Today users have a work around to this, that they can edit in workbench and remove the backticks for `window.start` command in MV

```
FROM:
CREATE MATERIALIZED VIEW myglue.default.mv_1
AS SELECT
   count(`@timestamp`) AS `counter1`, 
   `window.start`
FROM myglue.default.reddyvam
GROUP BY TUMBLE (`@timestamp`, '1 minute')
 WITH (
index_settings = '{"number_of_shards":1,"number_of_replicas":1}',
auto_refresh = true,
refresh_interval = '15 minutes',
watermark_delay = '1 minute',
checkpoint_location = 's3://ckpt'
)

TO:
CREATE MATERIALIZED VIEW myglue.default.mv_1
AS SELECT
   count(`@timestamp`) AS `counter1`, 
   window.start
FROM myglue.default.reddyvam
GROUP BY TUMBLE (`@timestamp`, '1 minute')
 WITH (
index_settings = '{"number_of_shards":1,"number_of_replicas":1}',
auto_refresh = true,
refresh_interval = '15 minutes',
watermark_delay = '1 minute',
checkpoint_location = 's3://ckpt'
)
```

**What is the expected behavior?**
The expected behavior is that the MV creation succeeds and `window.start` is quoted properly. 

**What is your host/environment?**
 - OS: Linux
 - Version: 2.13
 - Plugins: dashboards-observability

**Do you have any screenshots?**
Screenshot 2024-05-03 at 11 53 34 PM

**Do you have any additional context?**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by ps48**
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
(cherry picked from commit c7ee338cd882f0787e1537bc3924901682df085f)

### Description
Fix window start backtick during MV creation

### Issues Resolved
#1819 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by paulstn — APPROVED** [review]

**Review by mengweieric — APPROVED** [review]

File: public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/materialized_view/column_expression.tsx [hunk 1]
```diff
@@ -115,34 +115,39 @@ export const ColumnExpression = ({
...
-                        updateColumnExpressionValue(
-                          { ...currentColumnExpressionValue, functionParam: fieldOption[0].label },
-                          index
-                        )
-                      }
-                      isClearable={false}
-                    />
-                  </EuiFormRow>
-                </EuiFlexItem>
+                {currentColumnExpressionValue.functionName !== 'window.start' && (
```
Comment (joshuali925) [inline public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/materialized_view/column_expression.tsx:118]: would there be other similar functions like `window.start`?

**Review by joshuali925 — APPROVED** [review]

File: public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/materialized_view/column_expression.tsx (hunk 1 above)
Comment (ps48) [reply public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/materialized_view/column_expression.tsx:118]: no, this is the only unique aggregation with this special char on UI
