### PR TITLE
Integrations base path fix

### LINKED ISSUE #714: [BUG] Integrations plugin doesn't work if base path is configured
**What is the bug?**
When run with a base path, the integrations plugin fails in a few places. Images aren't loaded, and the "Try it" button fails as well.

**How can one reproduce the bug?**
1. Start OpenSearch Dashboards with `yarn start`. Normally we've developed with `--no-base-path`, and the test environments reflect this as well.

**What is the expected behavior?**
Regardless of if `--no-base-path` is passed or not, the plugin should function the same way.

**What is your host/environment?**
 - Mac
 - Commit 5c96cc62

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
N/A

### PR DESCRIPTION
**Pull request by Swiddis**
### Description
The assumption that dashboards would always be run with `--no-base-path` turns out to be false, so we need to update a few paths to apply the base path. This PR does those updates, switching from fetch to the http client for all API calls.

### Issues Resolved
#714 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: public/components/integrations/components/add_integration_flyout.tsx [hunk 1]
```diff
@@ -131,10 +131,16 @@ export function AddIntegrationFlyout(props: IntegrationFlyoutProps) {
   const fetchDataSourceMappings = async (
     targetDataSource: string
   ): Promise<{ [key: string]: { properties: any } } | null> => {
-    return fetch(`/api/console/proxy?path=${targetDataSource}/_mapping&method=GET`, {
-      method: 'POST',
-      headers: [['osd-xsrf', 'true']],
-    })
+    return fetch(
+      http.basePath.prepend(`/api/console/proxy?path=${targetDataSource}/_mapping&method=GET`),
```
Comment (joshuali925) [inline public/components/integrations/components/add_integration_flyout.tsx:135]: why is this going through console (devtools) 's api?

also i think if you use `http.get('/api/console')` or `http.get('./api/console')` it works without manually adding base path

File: public/components/integrations/components/add_integration_flyout.tsx [hunk 2]
```diff
@@ -131,10 +131,16 @@ export function AddIntegrationFlyout(props: IntegrationFlyoutProps) {
   const fetchDataSourceMappings = async (
     targetDataSource: string
   ): Promise<{ [key: string]: { properties: any } } | null> => {
-    return fetch(`/api/console/proxy?path=${targetDataSource}/_mapping&method=GET`, {
-      method: 'POST',
-      headers: [['osd-xsrf', 'true']],
-    })
+    return fetch(
```
Comment (joshuali925) [inline public/components/integrations/components/add_integration_flyout.tsx:134]: todo item fetch should be replaced by osd's http client. compatibility is better

File: public/components/integrations/components/add_integration_flyout.tsx [hunk 3]
```diff
@@ -91,7 +91,7 @@ export const doPropertyValidation = (
 };
 
 export function AddIntegrationFlyout(props: IntegrationFlyoutProps) {
-  const { onClose, onCreate, integrationName, integrationType } = props;
+  const { onClose, onCreate, integrationName, integrationType, http } = props;
```
Comment (joshuali925) [inline public/components/integrations/components/add_integration_flyout.tsx:94]: note only. clients/services like http might be better to be stored as context value or somewhere global. passing through props can get messy since many things need it

**Review by YANG-DB — APPROVED** [review]

File: public/components/integrations/components/add_integration_flyout.tsx (hunk 3 above)
Comment (ps48) [reply public/components/integrations/components/add_integration_flyout.tsx:94]: You can use this: https://github.com/opensearch-project/dashboards-observability/blob/main/public/framework/core_refs.ts

Comment (Swiddis) [reply public/components/integrations/components/add_integration_flyout.tsx:94]: Just switched to using coreRefs

**Review by derek-ho — APPROVED** [review]
