### PR TITLE
Fix index name collisions on integration sample creation.

### LINKED ISSUE #812: [BUG]Conflicting logs index templates
**What is the bug?**
when attempting to add multiple integrations that contain log templates - the patterns collide and prevent correct creation of the specific integration's log index template

**How can one reproduce the bug?**
Setup AWS-ELB integration
Setup Nginx integration
The logs index templates are conflicting since they both share the next index pattern:
```Json5
    "index_patterns": [
        "ss4o_logs-*-*"
    ],
    "data_stream": {},
    "template": {
   ....
```

**What is the expected behavior?**
Since the logs index templates are not created in advance for all types of possible log combinations, 
We need a clear distinction between each log associated for each integration:

1. Each integration will include the log mapping with a distinct name:
- ELB will contain `logs-elb` where the index pattern inside the index template will be

```Json5
    "index_patterns": [
        "ss4o_logs-elb-*"
    ],
    "data_stream": {},
    "template": {
   ....
```

- nginx will contain `logs-nginx` where the index pattern inside the index template will be
```Json5
    "index_patterns": [
        "ss4o_logs-nginx-*"
    ],
    "data_stream": {},
    "template": {
   ....
```

And so on for the rest of the common log index templates.
----

This will prevent the collision both in the index-pattern and both in the index mapping template name that will be very explicit for which integration it addresses - this also makes the template priority redundant ...

## Simplified query access
In addition to simplify the queries access to the index - each mapping will contain a shortened version of the index name - AKA alias:

For  `ss4o_logs-elb-*` the template will contain the next index alias:
```json5
    "aliases": {
      "logs-elb": {}
    },
```
This will simplify the queries and access patterns to the generated log indices and define the standard access convention in a meaningful format .

**Do you have any additional context?**
[Avoid index pattern collisions
](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html)

### PR DESCRIPTION
**Pull request by Swiddis**
### Description
When updating an index template with the same name, OpenSearch rejects the request if it invalidates any old indices. This affects the integration plugin's sample data creation, since it was previously only using type information for creating indices, and this led to collisions with index patterns. This PR also adds name information to the created indices, in order to avoid these collisions.

### Issues Resolved
Resolves #812 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: public/components/integrations/components/integration.tsx [hunk 1]
```diff
@@ -67,7 +67,7 @@ export function Integration(props: AvailableIntegrationProps) {
     } else {
       payload.index_patterns = [dataSourceName];
       return fetch(
-        `/api/console/proxy?path=_index_template/${componentName}_${version}&method=POST`,
+        `/api/console/proxy?path=_index_template/ss4o_${componentName}_${version}_${integration.name}&method=POST`,
```
Comment (YANG-DB) [inline public/components/integrations/components/integration.tsx:70]: why are we creating a unique component for each integration ?
we should not duplicate similar schema components (http, cloud, communication )
the code should first check is the component exists and verify it has the same version - if does nothing to update 
Otherwise - add the new template with (including the version as part of the template name)

**Review by YANG-DB — CHANGES_REQUESTED** [review]

File: public/components/integrations/components/integration.tsx (hunk 1 above)
Comment (Swiddis) [reply public/components/integrations/components/integration.tsx:70]: The part that creates non-duplicated components exists a few lines before this part, this is after component creation.

The issue only is with template creation, which *is* unique per-integration for most integrations, due to differing dependencies.

**Review by derek-ho — APPROVED** [review]

**Comment by YANG-DB** [comment]
please add a concrete example on how the index pattern that is explicitly Written in the index template is. being changed by the code - is this a good solution to change without allowing the user to be aware of this change ???

**Comment by Swiddis** [comment]
> please add a concrete example on how the index pattern that is explicitly Written in the index template is. being changed by the code - is this a good solution to change without allowing the user to be aware of this change ???

It only really affects which index the sample data is created in, the user is still expected to configure their own indices that follow the right conventions if they want to set up their own system. For running on prod, they'll want to remove all the sample data anyways, so it shouldn't really affect them?

**Review by YANG-DB — APPROVED** [review]
